Add controllers
Yabrov/java-shareit pull request #1
Opened 2023-02-18 15:01 UTC by Yabrov

Вроде все получилось. Не стал делать классы модели @Value, чтобы в дальнейшем иметь возможность обновлять сущности хибернейтом. Тесты не делал, т.к. в ТЗ сказано использовать тесты постмана.

2023-02-19 19:17 UTC, Donald522 requested changes
Привет.

Все очень хорошо. Написал пару комментариев как можно сократить код.

2023-02-19 19:17 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@AllArgsConstructor
Можно аннотацию Data использовать

2023-02-19 19:17 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/ItemExceptionController.java
> +public class ItemExceptionController {
На обычный Exception тоже лучше добавить обработчик

2023-02-19 19:17 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Item item = Item
А это почему не в маппере?

2023-02-19 19:17 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getAvailable() == null) {
У тебя е в контроллере есть аннотация Valid на itemDto
Почему эти проверки не делаются там?

2023-02-19 19:17 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                ? Collections.emptyList()
Мне кажется, что когда строка поиска не задана, то надо возвращать все

2023-02-19 19:17 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepository.java
> +        users.remove(user.getId());
Для пользователей мне кажется имеет смысл сделать soft delete

2023-02-19 19:17 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepository.java
> +    private final Map<String, Integer> emails = new HashMap<>();
За "индекс" по email лайк

2023-02-19 19:17 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User newUser = User
Тоже не понятно почему не в маппере.
И логичнее там этот код иметь, тут он вообще дублируется между update/create

2023-02-19 19:17 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (userDto.getEmail() == null) {
Почему аннотация Valid это не проверяет?

2023-02-19 19:17 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User user = userRepository.findUserById(userId);
А зачем делать find перед delete?
Кажется метод remove в мапе умеет возвращать то, что там было по ключу. Если вернулся null - значит не было ничего

2023-02-20 11:49 UTC, Yabrov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@AllArgsConstructor
Дело в том, что в дальнейшем этот класс будет @Entity, а там как я понял @Data использовать нежелательно.

2023-02-20 11:50 UTC, Yabrov commented on src/main/java/ru/practicum/shareit/item/ItemExceptionController.java
> +public class ItemExceptionController {
Он присутствует в UserExceptionController

2023-02-21 16:43 UTC, Yabrov commented
Привет! Многое подправил.

2023-02-21 16:44 UTC, Yabrov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User user = userRepository.findUserById(userId);
Однако нет, в таком случае тесты постмана завалятся

2023-02-21 16:44 UTC, Yabrov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (userDto.getEmail() == null) {
Подправил:)

2023-02-21 16:44 UTC, Yabrov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User newUser = User
Перенес в маппер

2023-02-21 19:57 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@AllArgsConstructor
А почему там Data использовать нежелательно?

2023-02-21 20:06 UTC, Donald522 reviewed
Привет!

Все ок, лайк

2023-02-21 20:07 UTC, Donald522 approved these changes
Привет!

Все ок, лайк

2023-02-22 15:14 UTC, Yabrov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@AllArgsConstructor
Потому что она генерит метод toString(), который приведет к принудительной загрузке "ленивых" связанных сущностей. А также она генерит equals() и hashcode(), которые для адекватной работы hibernate должны быть переопределены специальным образом. В следующем пул реквесте, все это постараюсь учесть.

2023-02-22 15:15 UTC, merged