Add bookings
Yabrov/java-shareit pull request #4
Opened 2023-03-03 16:16 UTC by Yabrov

2023-03-05 17:52 UTC, Donald522 requested changes
Привет!

По большому счету мне все нравится. Написал небольшие замечания.

2023-03-05 17:52 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/exceptions/BookingOverlapsException.java
> +    public BookingOverlapsException() {
booking_id тоже можно было бы добавить

2023-03-05 17:52 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/repository/DatabaseBookingRepositoryImpl.java
> +    public DatabaseBookingRepositoryImpl(@Lazy JpaBookingRepository bookingRepository) {
А зачем тут Lazy?

2023-03-05 17:52 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ItemNotFoundException(item.getId());
А почему нельзя бронить свою же вещь? 
Если и нельзя, то ошибка не очень подходящая, на мой взгляд.

2023-03-05 17:52 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        switch (bookingState) {
Этот switch явно просится вынести его в отдельный класс, потому что дублируется между 2 методами.
Я обычно такие вещи делаю так. Создаю интерфейс
```
BookingProvider {
  public Collection<BookingResponseDto> getAllBookingsOfUser(Long userId, String state);
  public Collection<BookingResponseDto> getAllBookingsForOwnerItems(Long userId, String state)
}
```

Этому репозиторию столько реализаций, сколько ветвей в switch + реализация - dispatcher, где собственно находится условие выбора. Это может switch либо же доставать нужную реализацию по ключу

```
public class BookingProviderSelector implements BookingProvider {
   private final Map<BookingState, BookingProvider> providers;

  public Collection<BookingResponseDto> getAllBookingsForOwnerItems(Long userId, String state) {
    // ....
    BookinkProvider provider = providers.get(state);
    provider.getAllBookingsForOwnerItems();
    //....
  }
}
```

2023-03-05 17:52 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private User owner;
Думаю имеет смысл сделать индекс по owner

2023-03-05 17:52 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return addNextAndLastBooking(addComments(itemMapper.convert(updatedItem)));
А откуда могут взяться комментарии к вещи, которую мы еще создали?

2023-03-05 17:52 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/repository/DatabaseItemRepositoryImpl.java
> +    public Item saveItem(Item item) {
Здесь Transactional уже не нужен.
Ты же открыл транзакцию из класса сервиса.

2023-03-05 17:52 UTC, Donald522 commented on src/main/resources/schema.sql
> +    booker_id  BIGINT                                  NOT NULL,
Мне кажется по этому полю тоже имеет смысл индекс добавить.
Мы же делаем запросы по нему.
Это осмысленное решение не добавлять?

2023-03-06 13:05 UTC, Yabrov commented
Все подправил. Спасибо за совет со switch, классный метод)

2023-03-06 17:14 UTC, Donald522 approved these changes
Привет,

все гуд, принимается

2023-03-06 17:14 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/provider/BookingProviderSelector.java
> +        providers.put(BookingState.PAST, pastBookingProvider);
Создание этой мапы можно вынести в java config и сюда инжектить бин

А то сейчас в ней не особо много смысла, учитывая, что ты и так все реализации сюда добавил)

2023-03-07 04:02 UTC, merged