Add item requests
Yabrov/java-shareit pull request #5
Opened 2023-03-15 10:18 UTC by Yabrov

Закончил работу над запросом вещи, пагинацией

2023-03-20 17:02 UTC, Yabrov commented
Привет! Закончил проект. Из-за плагинов, которые делаю checkstyle пришлось реализовать вручную функционал аннотации ломбока @With.

2023-03-21 16:24 UTC, Donald522 requested changes
Привет!

Все хорошо сделано, в тестах можно немного подсократить код разве что.
Насчет методов with - можно было наверное так не заморачиваться и использовать обычные сеттеры) А так очень много boilerplate кода пришлось написать

2023-03-21 16:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +        Booking booking = (Booking) SerializationUtils.clone(this);
С этим надо быть осторожным
Вот что пишут в документации:
```
This is many times slower than writing clone methods by hand on all objects in your object graph
```
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/SerializationUtils.html#clone-T-

2023-03-21 16:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/request/repository/JpaItemRequestRepository.java
> +    @Query("SELECT r FROM ItemRequest r LEFT JOIN FETCH r.items WHERE r.requestor = :requestor")
А hibernate сам этот запрос не построит?

2023-03-21 16:24 UTC, Donald522 commented on src/test/java/ru/practicum/shareit/controller/ItemRequestControllerTest.java
> +        mvc.perform(post("/requests")
Это можно вынести в отдельный метод, чтобы не дублировать между тестами

2023-03-21 16:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/config/IdReducer.java
> +public class IdReducer {
Если это используется только в тестах, то давай положим это к тестам
Такой код лучше не паковать в прод билд.

2023-03-22 18:28 UTC, Yabrov commented on src/main/java/ru/practicum/shareit/request/repository/JpaItemRequestRepository.java
> +    @Query("SELECT r FROM ItemRequest r LEFT JOIN FETCH r.items WHERE r.requestor = :requestor")
Точно) подправил)

2023-03-22 18:28 UTC, Yabrov commented on src/test/java/ru/practicum/shareit/controller/ItemRequestControllerTest.java
> +        mvc.perform(post("/requests")
Сделал

2023-03-22 18:31 UTC, Yabrov commented on src/main/java/ru/practicum/shareit/config/IdReducer.java
> +public class IdReducer {
Сделал)

2023-03-22 18:31 UTC, Yabrov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +        Booking booking = (Booking) SerializationUtils.clone(this);
Спасибо, буду иметь в виду.

2023-03-23 18:15 UTC, Donald522 approved these changes
Привет,
все окей)

2023-03-23 18:15 UTC, Donald522 commented on src/test/java/ru/practicum/shareit/controller/ItemRequestControllerTest.java
> +        mvc.perform(post("/requests")
Типа такого
```
private ResultActions performPostRequests() {
   return mvc.perform(post("/requests")
                        .header("X-Sharer-User-Id", xSharerUserId)
                        .content(mapper.writeValueAsString(itemRequestDto))
                        .characterEncoding(StandardCharsets.UTF_8)
                        .contentType(MediaType.APPLICATION_JSON)
                        .accept(MediaType.APPLICATION_JSON))
}
```

2023-03-25 07:42 UTC, merged