Add docker
Yabrov/java-shareit pull request #6
Opened 2023-03-31 10:52 UTC by Yabrov

2023-03-31 17:40 UTC, Yabrov commented
Привет! Постарался учесть все старые замечания.

2023-04-01 15:35 UTC, Donald522 requested changes
Привет!

Все хорошо, давай названия немного поправим только.

2023-04-01 15:35 UTC, Donald522 commented on docker-compose.yml
> +    image: postgres:13.7-alpine
А чего не 14 версия постгреса?

2023-04-01 15:35 UTC, Donald522 commented on docker-compose.yml
> +      - POSTGRES_USER=postgres
Обычно имя пользователя совпадает с именем приложения
Хорошим вариантом будет shareit_user или просто shareit

2023-04-01 15:35 UTC, Donald522 commented on docker-compose.yml
> +    build: server
Я бы назвал shareit-server

2023-04-01 15:35 UTC, Donald522 commented on docker-compose.yml
> +    build: gateway
Тут аналогично, лучше shareit-gateway

Названия должны быть максимально понятными

2023-04-01 17:27 UTC, Yabrov commented on docker-compose.yml
> +    build: gateway
Антон, подскажи, пожалуйста, как быть, если нужно, чтобы несколько приложений использовали один контейнер с постгресом, например. Тоесть имеется несколько независимых приложений, в каждом есть docker-compose файл. Как поднять конфиг, чтобы они работали с одним контейнером бд?

2023-04-02 08:06 UTC, Donald522 approved these changes

2023-04-02 08:06 UTC, Donald522 commented on docker-compose.yml
> +    build: gateway
Мне не приходилось делать такое, но вот я нашел feature request на эту тему
https://github.com/docker/compose/issues/2075

Насколько я понял, сейчас это решают с помощью external_links.

2023-04-03 05:19 UTC, merged